--- #YAML:1.0
name:                Sort-ByExample
version:             0.004
abstract:            sort lists to look like the example you provide
license:             perl
author:              
    - Ricardo SIGNES <rjbs@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Params::Util:                  0
    Sub::Exporter:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
