--- #YAML:1.0
name:               Sort-ByExample
version:            0.005
abstract:           sort lists to look like the example you provide
author:
    - Ricardo Signes <rjbs@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Params::Util:   0
    Sub::Exporter:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
